name: Create Draft Release
on:
  push:
    branches: [ release ]

  workflow_dispatch:


jobs:
  tag_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 12
    steps: 
    - uses: phish108/autotag-action@1.1.37
      with:
        bump: minor
        dry-run: true
        github-token: ${{ secrets.GITHUB_TOKEN}}
        with-v: true
  archive_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ${{ format('CAFE3_{0}.zip', steps.tag.outputs.new-tag) }}
        exclusions: '*.git*'
