name: Create Draft Release
on:
  push:
    branches: [ release ]

  workflow_dispatch:


jobs:
  tag_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 12
    env:
      bump: minor
      with-v: true
    steps: 
    - uses: phish108/autotag-action@1.1.37
      with:
        dry-run: false
        github-token: ${{ secrets.GITHUB_TOKEN}}
  archive_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ${{ format('CAFE3_{0}.zip', steps.tag.outputs.new-tag) }}
        exclusions: '*.git*'
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ format('CAFE3_{0}.zip', steps.tag.outputs.new-tag) }}
          tag: steps.tag.outputs.new-tag
          draft: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
