name: Create Draft Release
on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
  tag_release:
      runs-on: ubuntu-latest
      steps:
      - name: Bump version and push tag
      - uses: actions/checkout@v2
      - uses: mathieudutour/github-tag-action@v6.0   
        id: tag_version
        with:
          default_bump: 'minor'
          default_prerelease_bump: 'minor'
          tag_prefix: 'v'
          dry_run: false
          github_token: ${{ secrets.GITHUB_TOKEN }}    
      - run: echo ${{ steps.tag_version.outputs.new_tag }}   
  archive_release:
    runs-on: ubuntu-latest
    needs: tag_release
    steps:
    - run: echo ${{ needs.tag_release.steps.tag_version.outputs.new_tag }}
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ${{ format('CAFE3_{0}.zip', needs.tag_release.steps.tag_version.outputs.new_tag) }}
        exclusions: '*.git*'
  draft_release:
    runs-on: ubuntu-latest
    needs: [tag_release, archive_release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        env:
          tag: ${{ needs.tag_release.steps.tag_version.outputs.new_tag }}
        with:
          artifacts: ${{ format('CAFE3_{0}.zip', needs.tag_release.steps.tag_version.outputs.new_tag) }}
          draft: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
